### ISSUE TITLE
添加2.x HTMLRunnerCN之后，生成报告报错

### ISSUE THREAD

**Issue by LoveYouyou4Ever** [findyou/HTMLTestRunnerCN#15]
Traceback (most recent call last):
  File "F:/RRD/Tech/10.android ui�Զ���/Android-UI -20190410����/runner.py", line 33, in <module>
    runner.run(suite())
  File "C:\Python27\lib\HTMLTestRunner.py", line 573, in run
    self.generateReport(test, result)
  File "C:\Python27\lib\HTMLTestRunner.py", line 623, in generateReport
    report = self._generate_report(result)
  File "C:\Python27\lib\HTMLTestRunner.py", line 688, in _generate_report
    self._generate_report_test(rows, cid, tid, n, t, o, e)
  File "C:\Python27\lib\HTMLTestRunner.py", line 724, in _generate_report_test
    ue = e.decode('utf-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd7 in position 68: invalid continuation byte

**Comment by findyou** [comment]
常见的自行google一下
1、文件格式
2、编码问题
